### ISSUE TITLE
[Bug] Error in demo script - Method not found

### ISSUE THREAD

**Issue by devanshiAppperfect** [BattGenie/pymacnet#16]
**Error description -**
While executing the demo script , got a "Method not found" error in cell 9 for the read_status method for channel interface.

**Steps to reproduce -** 
1. Open the demo.ipynb file.
2. Start executing the cells one by one.
3. When reached at cell 9, the error will get triggered.

**Screenshot -**
![Screenshot 2023-12-21 at 2 47 45 PM](https://github.com/BattGenie/pymacnet/assets/111724834/132a5947-220e-4ea5-b84a-a5741e166766)

**Environment -**
1. Python - 3.11.6

**Comment by SyXuan** [comment]
Thanks for pointing out this bug!
