### ISSUE TITLE
[Question] Request for Guidance: Connecting to Maccor Library without Maccor Software/Hardware

### ISSUE THREAD

**Issue by devanshiAppperfect** [BattGenie/pymacnet#20]
Hello there !!

I currently do not have any Maccor cyclers or related software, but I am keen on connecting to the library through spoofers to retrieve data for further analysis. In this regard, I would greatly appreciate your assistance in providing information or scheduler files that could facilitate this process.

If there are any specific procedures or resources that I need to be aware of, please guide me accordingly. I am eager to explore the capabilities of the Maccor Library and leverage the data for my projects.

Additionally, if there is a sample piece of code that accomplishes a similar connection to the library for data retrieval using spoofers, it would be of great help in understanding the integration process. I am expecting of some random data to be generated.

Thanks.

**Comment by chintanp** [comment]
@devanshiAppperfect added a larger example for use of MaccorSpoofer and a video describing it use here: https://github.com/BattGenie/pymacnet?tab=readme-ov-file#maccorspoofer 

Let me know if have further questions.
